resource_group_name     = "Firstresource"
resource_group_location = "West Europe"
app_service_plan_name   = "FirstAppserviceplan"
app_service_name        = "temenosappservice"
sql_server_name         = "temenossqlserver"
sql_database_name       = "Firstsqldb"
sql_admin_login         = "deek"
sql_admin_password      = "milky@1993"
